### ISSUE TITLE
Deploy a new version of the site

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/aspen.io#1]
http://aspen.io/ really needs to be updated to reflect the big changes of the past few weeks.
### Todo
- [ ] are these really our backgrounds?
- [x] build Aspen, Pando and Simplates logos as SVG
- [x] clean up logo in footer
- [x] build out "flavor" cards
- [x] build "What is filesystem dispatch?" visualization
- [ ] reimplement "Impressions" client-side
- [x] ~~make /pando~~ https://github.com/AspenWeb/aspen.io/pull/2#issuecomment-245335876
- [x] ~~make /simplates~~ https://github.com/AspenWeb/aspen.io/pull/2#issuecomment-245335876
- [x] ~~are we templating these pages somehow?~~ https://github.com/AspenWeb/aspen.io/pull/2#issuecomment-245335876
- [ ] make it responsive
  - [ ] star buttons in framework listing
  - [ ] dispatch visual
  - [ ] body copy on FAQ
  - [ ] maybe use rems for text?
  - [ ] GitHub ribbon
- [x] syntax-highlight the simplates example (with what highlighter? 😞 )
- [ ] build out simplate support cards
- [ ] where do plugins fit?
- [x] favicon
- [ ] acknowledge sources (fonts, backgrounds, etc.(?))
- [ ] fix FOUC for star button
- [ ] test with multiple browsers

**Comment by Changaco** [comment]
First: do we want to import parts of the current content into this repo, or start from scratch?

**Comment by chadwhitacre** [comment]
@Changaco I say we start from scratch. I think aspen.io can now be a single static page, and all of the documentation that has been there can now be in Read the Docs for each subproject (aspen.py, Pando, Flask-Aspen, django-aspen, etc.).

**Comment by Changaco** [comment]
@whit537 Can you take this one? It'd be nice to deploy it at the same time we release the new aspen (and the first pando along if possible).

**Comment by chadwhitacre** [comment]
Sure thing. Do you have a timeframe in mind? We had [talked about](https://github.com/AspenWeb/pando.py/issues/357#issuecomment-181915970) September as a target for Aspen 1.0, though that was pre-Pando.

**Comment by Changaco** [comment]
Well, Aspen is pretty much ready, it even was before the last PR we just merged, and Pando should be similarly ready once https://github.com/AspenWeb/pando.py/pull/556 is merged, so really we could release soon. How about a 0.90 release for Aspen in the next few weeks, and 1.0 in September?

**Comment by chadwhitacre** [comment]
Note to self: don't forget to change security.txt (https://github.com/AspenWeb/salon/issues/3#issuecomment-241218751).

**Comment by chadwhitacre** [comment]
I'm taking this as my top-level ticket for what I need to get done before 1.0 (https://github.com/AspenWeb/pando.py/issues/357). I expect it to fan out into other work but fundamentally what we want to do on September 19 is be able to say "Hey check out http://aspen.io/ for the new Aspen 1.0 and friends!"

**Comment by chadwhitacre** [comment]
I think we need to come up with some realistic expectations about how much we're actually going to market and promote Aspen/Pando. I think the answer is "not very much." I'm not an /r/python regular and I'm not looking to be, to be honest. I'll talk about it some on Twitter, but I don't really want to pay attention to the [aspen_io](https://twitter.com/aspen_io) Twitter account.

**Comment by chadwhitacre** [comment]
Bringing this over from https://github.com/AspenWeb/aspen.py/pull/1#issuecomment-198488213:

![screen shot 2016-03-18 at 2 16 26 pm](https://cloud.githubusercontent.com/assets/134455/13887788/0d4fc860-ed14-11e5-927b-21ae04520b06.png)

**Comment by chadwhitacre** [comment]
... and this one from https://github.com/AspenWeb/salon/issues/1#issuecomment-185326588:

![photo on 2-17-16 at 12 59 pm](https://cloud.githubusercontent.com/assets/134455/13119282/5773fad4-d576-11e5-9d44-54b19d8ad560.jpg)

**Comment by chadwhitacre** [comment]
At this point I am leaning towards something like the latter, a visualization of the repos in our org, basically.

**Comment by chadwhitacre** [comment]
The former hints at same.

**Comment by chadwhitacre** [comment]
![11881599_888436087858628_857468899_n](https://cloud.githubusercontent.com/assets/134455/18298631/1a4a8ebe-7488-11e6-8def-b6ef9f63e61f.jpg)

https://www.instagram.com/p/7ZWW4mx8Bc/

**Comment by chadwhitacre** [comment]
![il_570xn 721617463_fvj0](https://cloud.githubusercontent.com/assets/134455/18298696/97627042-7488-11e6-8ec8-064bd0b541f6.jpg)

https://www.etsy.com/listing/221076543/block-print-bigtooth-aspen-leaf-limited

**Comment by chadwhitacre** [comment]
![populus-tremuloides-le-gmorrison](https://cloud.githubusercontent.com/assets/134455/18298792/3e7fd75c-7489-11e6-91b7-939111508bd7.jpg)

http://newfs.s3.amazonaws.com/taxon-images-1000s1000/Salicaceae/populus-tremuloides-le-gmorrison.jpg

**Comment by chadwhitacre** [comment]
![tree_bark](https://cloud.githubusercontent.com/assets/134455/18298813/6d36f512-7489-11e6-9eff-1dc61f96f5c0.png)

http://subtlepatterns.com/tree-bark/

**Comment by chadwhitacre** [comment]
![241](https://cloud.githubusercontent.com/assets/134455/18298838/9206118e-7489-11e6-95b2-7fc8f603f584.jpg)

http://photoephemeris.com/photographing-aspen

**Comment by chadwhitacre** [comment]
Repos:

```
        Flask-Aspen
        django-aspen
        pando.py
            aspen.py
                algorithm.py
                    dependency_injection.py
                filesystem_tree.py

        aspen.py-plugins

        aspen.go
        aspen.js
        aspen.rb

    aspen.io

        simplate.vim
        simplates.emacs

    simplates.org

salon
```

Should we rename `aspen.{go,js,rb}` to `pando.*`, or maybe simply get rid of them altogether?

Are `aspen.py-plugins` really still Aspen plugins? Is there more than one (Jinja2)?

**Comment by chadwhitacre** [comment]
There's a lot of work besides the Pando and Aspen 1.0 code itself to making this fly as an open source project:
- nice website
- documentation
- tutorials
- top users
- plugin ecosystem
- the Flask and Django shims
- simplate support for Vim and Emacs
- talking it up on /r/python, HN, Twitter, Changelog, Pycoders, StackOverflow, etc., etc.

**Comment by chadwhitacre** [comment]
![screen shot 2016-09-06 at 11 49 08 pm](https://cloud.githubusercontent.com/assets/134455/18299152/880f3356-748c-11e6-8795-8d6915cbb17f.png)

https://github.com/theleagueof/orbitron

**Comment by chadwhitacre** [comment]
Harumph. Too similar to Flask. :-/

![screen shot 2016-09-07 at 12 03 46 am](https://cloud.githubusercontent.com/assets/134455/18299399/9775416c-748e-11e6-8bcc-c71232645e5c.png)

![screen shot 2016-09-07 at 12 04 08 am](https://cloud.githubusercontent.com/assets/134455/18299415/b1bd67b6-748e-11e6-92e6-3e1b58e8be8e.png)

**Comment by chadwhitacre** [comment]
![screen shot 2016-09-07 at 12 13 00 am](https://cloud.githubusercontent.com/assets/134455/18299570/e2466bd4-748f-11e6-8f12-0152188014ec.png)

**Comment by chadwhitacre** [comment]
![screen shot 2016-09-07 at 12 29 08 am](https://cloud.githubusercontent.com/assets/134455/18299837/2253ba0e-7492-11e6-8d9f-eaf944a26287.png)

**Comment by chadwhitacre** [comment]
![screen shot 2016-09-07 at 12 30 25 am](https://cloud.githubusercontent.com/assets/134455/18299852/5229eb72-7492-11e6-931e-a85b7b19600b.png)

**Comment by chadwhitacre** [comment]
![screen shot 2016-09-07 at 12 32 07 am](https://cloud.githubusercontent.com/assets/134455/18299885/8a29355a-7492-11e6-9c3c-6ed729a762ba.png)

**Comment by chadwhitacre** [comment]
![screen shot 2016-09-07 at 12 33 01 am](https://cloud.githubusercontent.com/assets/134455/18299907/a8a20eb2-7492-11e6-9aa3-b98e5d814d28.png)

**Comment by chadwhitacre** [comment]
![screen shot 2016-09-07 at 1 31 40 am](https://cloud.githubusercontent.com/assets/134455/18300849/db3c191e-749a-11e6-9edf-df54796ffae6.png)

http://subtlepatterns.com/seamless-paper-texture/

**Comment by chadwhitacre** [comment]
https://github.com/theleagueof/blackout
https://github.com/theleagueof/league-spartan

**Comment by chadwhitacre** [comment]
![screen shot 2016-09-07 at 2 43 26 am](https://cloud.githubusercontent.com/assets/134455/18302271/ea2622c6-74a4-11e6-98dc-56e23867a253.png)

**Comment by chadwhitacre** [comment]
We'll need to kern these, but I like how they're lining up. Aspen, Pando, and Simplates all share the distinctive A and P from Blackout.

**Comment by chadwhitacre** [comment]
![5csntr8mni](https://cloud.githubusercontent.com/assets/134455/18302423/da5d21f4-74a5-11e6-80da-0cc8eade1755.gif)

**Comment by Changaco** [comment]
> Should we rename `aspen.{go,js,rb}` to `pando.*`, or maybe simply get rid of them altogether?

I suggest doing nothing other than changing the repo descriptions.

> Are `aspen.py-plugins` really still Aspen plugins?

Yes, because simplates haven't been cut out of aspen yet.

> Is there more than one (Jinja2)?

Yes, there's a tornado renderer that still works (at least in the tests).

**Comment by chadwhitacre** [comment]
[![Travis CI](https://cloud.githubusercontent.com/assets/134455/18312567/6d19ccc2-74d8-11e6-9b4d-cdcd043773a6.png)](https://travis-ci.com/)

[![npm](https://cloud.githubusercontent.com/assets/134455/18312568/6d1ab5e2-74d8-11e6-8934-96c0b7a90c72.png)](https://www.npmjs.com/)

[![Docker](https://cloud.githubusercontent.com/assets/134455/18312572/6d266e14-74d8-11e6-8c33-f0bcf5a1f2e1.png)](https://www.docker.com/)

[![Meteor](https://cloud.githubusercontent.com/assets/134455/18312571/6d1c2e22-74d8-11e6-8fc1-909f60cfe05d.png)](https://www.meteor.com/)

[![Ruby on Rails](https://cloud.githubusercontent.com/assets/134455/18312569/6d1afd2c-74d8-11e6-9907-c9d8829f6c97.png)](http://rubyonrails.org/)

**Comment by chadwhitacre** [comment]
[![Hashicorp](https://cloud.githubusercontent.com/assets/134455/18312732/2e182acc-74d9-11e6-94b3-91f9faa2ecce.png)](https://www.hashicorp.com/)

[![Vagrant](https://cloud.githubusercontent.com/assets/134455/18312733/2e1b0db4-74d9-11e6-8e75-82fb5dca929a.png)](https://www.vagrantup.com/)

[![Packer](https://cloud.githubusercontent.com/assets/134455/18312735/2e1e86e2-74d9-11e6-8f57-318ec0a267c5.png)](https://www.packer.io/)

[![Serf](https://cloud.githubusercontent.com/assets/134455/18312737/2e22941c-74d9-11e6-99c9-e7bc86bf4037.png)](https://www.serf.io/)

[![Consul](https://cloud.githubusercontent.com/assets/134455/18312736/2e1ee218-74d9-11e6-8607-115ce2615874.png)](https://www.consul.io/)

[![Terraform](https://cloud.githubusercontent.com/assets/134455/18312738/2e23fa14-74d9-11e6-84e6-fb3d2168debe.png)](https://www.terraform.io/)

[![Vault](https://cloud.githubusercontent.com/assets/134455/18312741/2e25c6b4-74d9-11e6-9cfa-3c521f916c26.png)](https://www.vaultproject.io/)

[![Nomad](https://cloud.githubusercontent.com/assets/134455/18312740/2e259bbc-74d9-11e6-85e0-238fa8f47e6b.png)](https://www.nomadproject.io/)

**Comment by chadwhitacre** [comment]
![aspenbark](https://cloud.githubusercontent.com/assets/134455/18318673/9f758950-74f0-11e6-9d34-7a71b063150a.jpg)

http://plantsandrocks.blogspot.com/2012/10/final-trek.html

**Comment by chadwhitacre** [comment]
![mt-20080928-101929-0008-edit-colorado-golden-aspen-leaf-bark](https://cloud.githubusercontent.com/assets/134455/18318830/2ab86190-74f1-11e6-9fdf-f244812bf4fa.jpg)

https://www.montetrumbull.com/galleries/05-close-to-nature/

**Comment by chadwhitacre** [comment]
I'm thinking of having pages for http://aspen.io/pando and http://aspen.io/simplates, redirecting http://simplates.org/ to the latter.

**Comment by chadwhitacre** [comment]
Moving to https://github.com/AspenWeb/aspen.io/pull/2 and closing here.

**Comment by chadwhitacre** [comment]
Reopening per https://github.com/AspenWeb/aspen.io/pull/2#issuecomment-245392918.

**Comment by chadwhitacre** [comment]
I moved `aspen.io` and `simplates.org` from Gratipay's DNSimple account to my personal account. I had to sign up for the $5/mo plan to do so.

**Comment by chadwhitacre** [comment]
💃

![screen shot 2016-09-07 at 3 45 51 pm](https://cloud.githubusercontent.com/assets/134455/18326095/38bacadc-7512-11e6-99e4-60a728b4f826.png)

**Comment by chadwhitacre** [comment]
New site is up on http://new.aspen.io/. Will keep iterating there ...

**Comment by chadwhitacre** [comment]
Now actually reopening. 😊

**Comment by chadwhitacre** [comment]
Django and Pando sure share a lotta letters. 😳

**Comment by chadwhitacre** [comment]
Cleaned up the frameworks listing.

![screen shot 2016-09-08 at 12 18 22 am](https://cloud.githubusercontent.com/assets/134455/18336926/d37e9f7a-7559-11e6-94bb-4aa34d4458b4.png)

**Comment by Changaco** [comment]
> - syntax-highlight the simplates example (with what highlighter? :disappointed: )

I've had [syntax highlighting of simplates in Kate](https://github.com/Changaco/kate-highlightings/blob/master/simplate.xml) for a while, and it supports exporting to HTML. Also, [pandoc](http://pandoc.org/) generates its highlighting code using Kate's syntax files, but you'd need to compile it yourself to add the simplates syntax.

**Comment by Changaco** [comment]
Here's the simplate example (modified to use Jinja2 for the HTML page) highlighted by Kate using 3 different themes:

``` html
<h2>Theme: Normal</h2>

<pre style='color:#1f1c1b;background-color:#ffffff;'>
<span style='color:#ff5500;'>import</span> random

<span style='color:#0057ae;background:#e0e9f8;'>[----]</span>
program <b>=</b> request.qs[<span style='color:#bf0303;'>'program'</span>]
excitement <b>=</b> <span style='color:#bf0303;'>&quot;!&quot;</span> <b>*</b> random.randint(<span style='color:#b08000;'>1</span>, <span style='color:#b08000;'>10</span>)

<span style='color:#0057ae;background:#e0e9f8;'>[----] text/html via jinja2</span>
<b>&lt;h1&gt;</b>Greetings, {{ program }}{{ excitement }}<b>&lt;/h1&gt;</b>

<span style='color:#0057ae;background:#e0e9f8;'>[----] text/plain via stdlib_format</span>
Greetings, {program}{excitement}

<span style='color:#0057ae;background:#e0e9f8;'>[----] application/json via json_dump</span>
{ &quot;program&quot;: program
, &quot;excitement&quot;: excitement
 }
</pre>

<h2>Theme: Breeze Dark</h2>

<pre style='color:#cfcfc2;background-color:#232629;'>
<span style='color:#27ae60;'>import</span> random

<span style='color:#2980b9;background:#153042;'>[----]</span>
program = request.qs[<span style='color:#f44f4f;'>'program'</span>]
excitement = <span style='color:#f44f4f;'>&quot;!&quot;</span> * random.randint(<span style='color:#f67400;'>1</span>, <span style='color:#f67400;'>10</span>)

<span style='color:#2980b9;background:#153042;'>[----] text/html via jinja2</span>
<b>&lt;h1&gt;</b>Greetings, {{ program }}{{ excitement }}<b>&lt;/h1&gt;</b>

<span style='color:#2980b9;background:#153042;'>[----] text/plain via stdlib_format</span>
Greetings, {program}{excitement}

<span style='color:#2980b9;background:#153042;'>[----] application/json via json_dump</span>
{ &quot;program&quot;: program
, &quot;excitement&quot;: excitement
 }
</pre>

<h2>Theme: Vim</h2>

<pre style='font-weight:bold;color:#b2b2b2;background-color:#000000;'>
<b><span style='color:#ff54ff;'>import</span></b><b> random</b>

<b><span style='color:#0095ff;background:#22226d;'>[----]</span></b>
<b>program </b><b>=</b><b> request.qs[</b><b><span style='color:#ff54ff;'>'program'</span></b><b>]</b>
<b>excitement </b><b>=</b><b> </b><b><span style='color:#ff54ff;'>&quot;!&quot;</span></b><b> </b><b>*</b><b> random.randint(</b><b><span style='color:#ff54ff;'>1</span></b><b>, </b><b><span style='color:#ff54ff;'>10</span></b><b>)</b>

<b><span style='color:#0095ff;background:#22226d;'>[----] text/html via jinja2</span></b>
<b><span style='color:#dede49;'>&lt;h1&gt;</span></b><b>Greetings, {{ program }}{{ excitement }}</b><b><span style='color:#dede49;'>&lt;/h1&gt;</span></b>

<b><span style='color:#0095ff;background:#22226d;'>[----] text/plain via stdlib_format</span></b>
Greetings, {program}{excitement}

<b><span style='color:#0095ff;background:#22226d;'>[----] application/json via json_dump</span></b>
{ &quot;program&quot;: program
, &quot;excitement&quot;: excitement
 }
</pre>
```

![example spt html-2016-09-08](https://cloud.githubusercontent.com/assets/1581590/18344253/c514a5b2-75b6-11e6-8022-cfde38a2d6d3.png)

**Comment by chadwhitacre** [comment]
> Here's the simplate example (modified to use Jinja2 for the HTML page) highlighted by Kate using 3 different themes:

!m @Changaco 💃 

Updated in 6bc96c20635ae680f4c76c84aba80e4e90aff0c7.

**Comment by chadwhitacre** [comment]
The plugins should all get their own RtD subsite under `aspen.io` as well.

**Comment by chadwhitacre** [comment]
@Changaco You okay with what is apparently our new logo? You okay with how the new homepage is shaping up?

![screen shot 2016-09-08 at 10 27 47 pm](https://cloud.githubusercontent.com/assets/134455/18373616/8f8d1f02-7613-11e6-9446-d56d4b6801c4.png)

**Comment by chadwhitacre** [comment]
Here's the 512 PNG that I used for GitHub:

![512](https://cloud.githubusercontent.com/assets/134455/18373713/8082937e-7614-11e6-9653-1350a83df959.png)

**Comment by Changaco** [comment]
> You okay with what is apparently our new logo? You okay with how the new homepage is shaping up?

Yes and yes, although the completely blacked-out PANDO logo looks weird to me.

**Comment by chadwhitacre** [comment]
http://qrohlf.com/trianglify/
